"""Build configs/datasets/cear_index.yaml — CEAR's download catalog (sequence -> Drive IDs).

This is the ONLY CEAR-specific download code: it parses the dataset's public download pages, where
every sequence is listed as  "<name>  Data(<size>GB)  GT_pose"  with Google Drive links (Data is one
archive file; GT_pose is a Drive folder or a single file). The resulting index is plain data that
the generic scripts/fetch_sequence.py consumes — another dataset just ships its own index.

Re-run if CEAR changes its links:
    python scripts/build_cear_index.py --out configs/datasets/cear_index.yaml
"""
from __future__ import annotations
import argparse, html, re, sys, urllib.request

PAGES = ["https://daroslab.github.io/cear/Downloads/indoorsequence/",
         "https://daroslab.github.io/cear/Downloads/outdoorsequence/",
         "https://daroslab.github.io/cear/Downloads/backflipsequence/"]
_ROW = re.compile(r'([A-Za-z0-9_\-]+)\s*\{Data\(([\d.]+)GB\)=>((?:d|folders)/[^}]+)\}\s*\{GT_[Pp]ose=>((?:d|folders)/[^}]+)\}')


def _drive(ref: str) -> dict:
    kind, gid = ref.split("/", 1)
    return {"gdrive_folder": gid} if kind == "folders" else {"gdrive": gid}


def parse(page_html: str) -> dict:
    raw = re.sub(r"<(script|style)[^>]*>.*?</\1>", " ", page_html, flags=re.S)

    def link(m):
        ref = re.search(r"/d/([^/?]+)|folders/([^?/]+)", m.group(1))
        ref = f"d/{ref.group(1)}" if ref.group(1) else f"folders/{ref.group(2)}"
        return " {" + re.sub("<[^>]+>", "", m.group(2)).strip() + "=>" + ref + "} "

    raw = re.sub(r'<a [^>]*href="(https://drive\.google\.com/[^"]+)"[^>]*>(.*?)</a>', link, raw, flags=re.S)
    text = re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", raw)))
    return {name: {"size_gb": float(size), "data": _drive(data), "gt_pose": _drive(gt)}
            for name, size, data, gt in _ROW.findall(text)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    import yaml
    index = {}
    for url in PAGES:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        rows = parse(urllib.request.urlopen(req, timeout=60).read().decode("utf-8", "ignore"))
        print(f"[index] {url}: {len(rows)} sequences")
        index.update(rows)
    if not index:
        print("[index] ERROR: parsed 0 sequences — the page layout changed"); return 1
    with open(args.out, "w") as f:
        f.write("# CEAR download catalog, generated by scripts/build_cear_index.py — do not edit by hand.\n")
        yaml.safe_dump({"sequences": dict(sorted(index.items()))}, f, sort_keys=False, width=120)
    print(f"[index] wrote {len(index)} sequences -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
