"""Download one sequence's raw data from the dataset's download index (generic, no dataset code).

Replaces the manual "gdown <link> && unzip" step. The dataset config points at an index:

  download.index   path (relative to the repo) of a YAML {sequences: {<name>: {<item>: <source>}}}
                   where each source is {gdrive: <file id>} | {gdrive_folder: <id>} | {url: ...}
                   (CEAR's is generated by scripts/build_cear_index.py; items = data + gt_pose)

Files are downloaded to a staging dir; archives (zip/tar) are unpacked; the directory holding the
sequence (the one containing sequence.rgb_dir and sequence.timestamp_table) is moved to
sequence.data_root, and sequence.pose_file is located and placed there. Idempotent: if data_root
already has the pose file, rgb dir and timestamp table, nothing is downloaded. Checks free disk first.

    python scripts/fetch_sequence.py --config configs/<seq>.yaml
"""
from __future__ import annotations
import argparse, os, shutil, sys, tarfile, zipfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pose_utils as pu

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _complete(root, seq):
    need = [seq["pose_file"], seq.get("rgb_dir", "rgb"), seq["timestamp_table"]]
    return [n for n in need if not os.path.exists(os.path.join(root, n))]


def _find(top, pred):
    for dirpath, dirnames, filenames in os.walk(top):
        if pred(dirpath, dirnames, filenames):
            return dirpath
    return None


def _unpack(path, dest):
    if zipfile.is_zipfile(path):
        with zipfile.ZipFile(path) as z:
            z.extractall(dest)
        return True
    if tarfile.is_tarfile(path):
        with tarfile.open(path) as t:
            t.extractall(dest, filter="data")
        return True
    return False


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--keep-archives", action="store_true")
    args = ap.parse_args()
    import gdown, yaml

    cfg = pu.load_config(args.config)
    seq = cfg["sequence"]; name = seq["name"]; root = seq["data_root"]
    missing = _complete(root, seq)
    if not missing:
        print(f"[fetch] {name}: data present at {root}"); return 0
    dl = cfg.get("download") or {}
    if not dl.get("index"):
        print(f"[fetch] ERROR: {name} is missing {missing} and the config has no download.index"); return 2
    idx_path = dl["index"] if os.path.isabs(dl["index"]) else os.path.join(REPO, dl["index"])
    entry = (yaml.safe_load(open(idx_path)).get("sequences") or {}).get(name)
    if not entry:
        print(f"[fetch] ERROR: {name} not in {idx_path}"); return 2

    size_gb = float(entry.get("size_gb", 0))
    free_gb = shutil.disk_usage(os.path.dirname(root) or ".").free / 1e9
    if size_gb and free_gb < 2.5 * size_gb:
        print(f"[fetch] ERROR: need ~{2.5*size_gb:.0f} GB free for {name} (archive + unpacked), have {free_gb:.0f} GB")
        return 2
    stage = os.path.join(os.path.dirname(root), "_downloads", name)
    os.makedirs(stage, exist_ok=True); os.makedirs(root, exist_ok=True)
    print(f"[fetch] {name} ({size_gb} GB) -> {root}  (missing: {missing})", flush=True)

    # optional signed-in Google session (Netscape cookie file) — lifts Drive's anonymous download quota
    cookies = os.environ.get("GDRIVE_COOKIES") or None
    kw = dict(quiet=True, retries=3, cookies_file=cookies)
    for item, src in entry.items():
        if item == "size_gb":
            continue
        try:
            if "gdrive_folder" in src:
                print(f"[fetch] {item}: Drive folder -> {root}", flush=True)
                gdown.download_folder(id=src["gdrive_folder"], output=root, **kw)
                continue
            print(f"[fetch] {item}: downloading", flush=True)
            path = (gdown.download(id=src["gdrive"], output=stage + os.sep, **kw) if "gdrive" in src
                    else gdown.download(url=src["url"], output=stage + os.sep, **kw))
        except Exception as ex:  # noqa: BLE001 — gdown raises several types for quota / permission
            reason = str(ex).strip().splitlines()[0] if str(ex).strip() else type(ex).__name__
            print(f"[fetch] ERROR: the host refused '{item}' for {name}: {reason}\n"
                  f"  This is the dataset host's download limit, not a pipeline error. Either:\n"
                  f"    - rerun later (Drive quotas reset within ~24 h; finished steps are skipped), or\n"
                  f"    - use a signed-in Google session: export Drive cookies (Netscape format) to a file\n"
                  f"      and rerun with GDRIVE_COOKIES=<that file>")
            return 3
        if not path or not os.path.exists(path):
            print(f"[fetch] ERROR: download of {item} failed (Drive quota or link change?)"); return 1
        if _unpack(path, os.path.join(stage, "unpacked")):
            print(f"[fetch] {item}: unpacked {os.path.basename(path)}", flush=True)
            if not args.keep_archives:
                os.remove(path)
        else:
            shutil.move(path, os.path.join(root, os.path.basename(path)))

    # move the unpacked sequence directory into data_root
    rgb = seq.get("rgb_dir", "rgb")
    src_dir = _find(os.path.join(stage, "unpacked"),
                    lambda d, dn, fn: rgb in dn and seq["timestamp_table"] in fn)
    if src_dir:
        for child in os.listdir(src_dir):
            dst = os.path.join(root, child)
            if not os.path.exists(dst):
                shutil.move(os.path.join(src_dir, child), dst)
    # place the pose file at data_root/<pose_file>
    pose = os.path.join(root, seq["pose_file"])
    if not os.path.exists(pose):
        hit = _find(root, lambda d, dn, fn: seq["pose_file"] in fn) or _find(stage, lambda d, dn, fn: seq["pose_file"] in fn)
        if hit:
            shutil.move(os.path.join(hit, seq["pose_file"]), pose)
    shutil.rmtree(os.path.join(stage, "unpacked"), ignore_errors=True)

    missing = _complete(root, seq)
    if missing:
        print(f"[fetch] ERROR: after download {name} still lacks {missing} — inspect {root} and {stage}")
        return 1
    print(f"[fetch] {name}: ready at {root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
