#!/usr/bin/env python3
"""Build a single self-contained results.html (videos + frames base64-embedded).

One portable file — open it in VS Code's Simple Browser, download it, or serve it with
`python -m http.server`. No external assets, so it works anywhere.

    python scripts/make_gallery.py --seq mocap1_well-lit_trot --out results/results.html
"""
from __future__ import annotations
import argparse, base64, glob, os, mimetypes


def b64(path):
    mime = mimetypes.guess_type(path)[0] or "application/octet-stream"
    with open(path, "rb") as f:
        return f"data:{mime};base64," + base64.b64encode(f.read()).decode()


def find(*cands):
    for c in cands:
        hits = sorted(glob.glob(c))
        if hits:
            return hits[0]
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seq", default="mocap1_well-lit_trot")
    ap.add_argument("--repo", default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    ap.add_argument("--out", default=None)
    args = ap.parse_args()
    repo = args.repo
    ws = os.environ.get("CEAR_WS", "/scratch4/workspace/%s-cear" % os.environ.get("USER", ""))
    nav = f"{ws}/outputs/{args.seq}"
    out = args.out or os.path.join(repo, "results", "results.html")
    os.makedirs(os.path.dirname(out), exist_ok=True)

    # locate assets (durable /work copies first, then scratch)
    robot_vid = find(f"{repo}/results/robot_in_splat.mp4", f"{nav}/navsplat/robot_in_splat.mp4")
    walk_vid  = find(f"{repo}/results/walkthrough.mp4", f"{nav}/walkthrough.mp4")
    hero      = find(f"{repo}/docs/figures/robot_in_splat_hero.png", f"{nav}/navsplat/nav_0012.png")
    proof     = find(f"{repo}/docs/figures/nurec_render_proof.png")
    onoff     = find(f"{repo}/docs/figures/mocap1_onpath_vs_offpath.png")

    cards = []
    def vid_card(title, desc, path):
        if not path or not os.path.exists(path): return
        cards.append(f"""<section class="card"><h2>{title}</h2><p>{desc}</p>
          <video controls loop autoplay muted playsinline src="{b64(path)}"></video></section>""")
    def img_card(title, desc, path):
        if not path or not os.path.exists(path): return
        cards.append(f"""<section class="card"><h2>{title}</h2><p>{desc}</p>
          <img src="{b64(path)}"></section>""")

    vid_card("🤖 Robot navigating the photoreal world",
             "A physics-lit robot composited into the Gaussian-splat reconstruction of the CEAR "
             "scene, rendered in Isaac Sim 6.1.0 (NuRec neural volume rendering).", robot_vid)
    img_card("Hero frame", "Single frame — the robot is a real 3D object in the reconstructed scene "
             "(lit top face, shaded sides), with gaussians blending at its edge.", hero)
    vid_card("🌍 Photoreal walkthrough of the reconstructed world",
             "90-frame fly-through along the recorded trajectory. Soft/hazy because mocap1 is a "
             "dense foliage scene reconstructed from RGB+depth only — the data-limited reality.", walk_vid)
    img_card("NuRec render proof", "Our exported .usdz rendered by NVIDIA's own nurec_render.py at a "
             "recorded pose — confirms the asset + renderer are correct.", proof)
    img_card("Reconstruction quality (on-path vs off-path)",
             "The splat is faithful on the recorded path and degrades off it — a coverage limit of "
             "the single-sequence data, not the renderer.", onoff)

    body = "\n".join(cards) or "<p>No assets found. Run a render first (see docs/RUN.md).</p>"
    html = f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CEAR → Splat → Isaac — results</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: system-ui, sans-serif; margin: 0; background: #0f1115; color: #e8e8ea; }}
  header {{ padding: 28px 24px; background: linear-gradient(135deg,#1b2333,#0f1115); border-bottom:1px solid #222; }}
  header h1 {{ margin: 0 0 6px; font-size: 22px; }}
  header p {{ margin: 0; color: #9aa4b2; font-size: 14px; }}
  main {{ max-width: 900px; margin: 0 auto; padding: 20px; }}
  .card {{ background:#151922; border:1px solid #232a36; border-radius:12px; padding:18px; margin:18px 0; }}
  .card h2 {{ margin: 0 0 6px; font-size: 17px; }}
  .card p {{ margin: 0 0 12px; color:#9aa4b2; font-size:13.5px; line-height:1.5; }}
  video, img {{ width: 100%; border-radius: 8px; background:#000; display:block; }}
  footer {{ text-align:center; color:#6b7280; font-size:12px; padding: 24px; }}
</style></head><body>
<header><h1>CEAR → Gaussian Splat → Isaac Sim</h1>
<p>mocap1 quadruped sequence reconstructed from RGB+depth+poses (no LiDAR), rendered with NuRec in Isaac Sim 6.1.0.</p></header>
<main>{body}</main>
<footer>Self-contained — every asset is embedded. Generated by scripts/make_gallery.py</footer>
</body></html>"""
    with open(out, "w") as f:
        f.write(html)
    print(f"wrote {out} ({os.path.getsize(out)//1024} KB, {len(cards)} cards)")


if __name__ == "__main__":
    main()
